Repository dasch-swiss/knora-ui, pull requests merged in 2018-12, with the labels that each got.

#133 Extended Search Params Service
  projects/knora/core/src/lib/services/v2/search-params.service.spec.ts
  projects/knora/core/src/lib/services/v2/search-params.service.ts
  src/app/knora-ui-examples/search-demo/search-result/search-result.component.ts
Labels: bug

#131 Improve unit testing of knora/action module
  projects/knora/action/src/lib/action.module.ts
  projects/knora/action/src/lib/admin-image/admin-image.directive.spec.ts
  projects/knora/action/src/lib/existing-name/existing-name.directive.spec.ts
  projects/knora/action/src/lib/pipes/key.pipe.spec.ts
  projects/knora/action/src/lib/pipes/reverse.pipe.spec.ts
  projects/knora/action/src/lib/pipes/sort-by.pipe.spec.ts
  projects/knora/action/src/lib/pipes/sort-by.pipe.ts
  projects/knora/action/src/lib/progress-indicator/progress-indicator.component.spec.ts
  projects/knora/action/src/lib/resource-dialog/resource-dialog.component.spec.ts
  projects/knora/action/src/lib/sort-button/sort-button.component.spec.ts
  projects/knora/action/src/public_api.ts
Labels: testing

#139 Viewer: add test for string containing special chars in HTML
  projects/knora/viewer/src/lib/property/text-value/text-value-as-string/text-value-as-string.component.spec.ts
Labels: testing

#137 Prefix in library components, directives of @knora/action
  projects/knora/action/README.md
  projects/knora/action/src/lib/directives/gnd.directive.ts
  projects/knora/action/src/lib/directives/jdn-datepicker.directive.ts
  projects/knora/action/src/lib/pipes/key.pipe.ts
  projects/knora/action/src/lib/pipes/reverse.pipe.ts
  projects/knora/action/src/lib/pipes/sort-by.pipe.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/date-value.component.html
  projects/knora/search/src/lib/search.component.html
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.html
  src/app/knora-ui-examples/action-demo/key/key.component.html
  src/app/knora-ui-examples/action-demo/key/key.component.ts
  src/app/knora-ui-examples/action-demo/sort-button/sort-button.component.html
  src/app/knora-ui-examples/action-demo/sort-button/sort-button.component.ts
  src/app/knora-ui-examples/core-demo/resource/resource.component.html
  src/app/knora-ui-examples/search-demo/search-result/search-result.component.html
  src/app/partials/module-index/module-index.component.html
Labels: refactor
