Repository dasch-swiss/knora-ui, pull requests merged in 2018-10, with the labels that each got.

#86 Core module: date format
  projects/knora/core/src/lib/declarations/api/shared/date.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.ts
  projects/knora/core/src/lib/declarations/index.ts
  projects/knora/viewer/src/lib/property/date-value/date-value.component.html
  projects/knora/viewer/src/lib/property/date-value/date-value.component.spec.ts
  projects/knora/viewer/src/lib/property/date-value/date-value.component.ts
  projects/knora/viewer/src/lib/property/link-value/link-value.component.ts
  src/app/knora-ui-examples/core-demo/resource/resource.component.html
  src/app/knora-ui-examples/core-demo/resource/resource.component.ts
  src/app/knora-ui-examples/viewer-demo/properties/properties.component.html
  src/app/knora-ui-examples/viewer-demo/properties/properties.component.ts
Labels: enhancement

#90 Action module: Delete MathJax directive
  projects/knora/action/src/lib/action.module.ts
  projects/knora/action/src/lib/directives/mathjax.directive.spec.ts
  projects/knora/action/src/lib/directives/mathjax.directive.ts
  projects/knora/action/src/public_api.ts
  projects/knora/viewer/src/lib/property/list-value/list-value.component.html
  projects/knora/viewer/src/lib/property/text-value/text-value-as-html/text-value-as-html.component.html
Labels: enhancement

#89 Core module: add missing services
  projects/knora/core/README.md
  projects/knora/core/src/lib/declarations/api/admin/lists/list-node-info.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/lists-response.ts
  projects/knora/core/src/lib/services/admin/language.service.spec.ts
  projects/knora/core/src/lib/services/admin/language.service.ts
  projects/knora/core/src/lib/services/admin/lists.service.spec.ts
  projects/knora/core/src/lib/services/admin/lists.service.ts
  projects/knora/core/src/lib/services/admin/status-msg.service.spec.ts
  projects/knora/core/src/lib/services/admin/status-msg.service.ts
  projects/knora/core/src/lib/services/index.ts
  projects/knora/core/src/lib/services/v2/basic-ontology.service.spec.ts
  projects/knora/core/src/lib/services/v2/basic-ontology.service.ts
  projects/knora/core/src/lib/services/v2/resource-types.service.spec.ts
  projects/knora/core/src/lib/services/v2/resource-types.service.ts
  projects/knora/core/src/lib/services/v2/store.service.spec.ts
  projects/knora/core/src/lib/services/v2/store.service.ts
  projects/knora/core/src/lib/test-data/admin/shared-test-data.ts
  src/app/knora-ui-examples/core-demo/lists/lists.component.html
  src/app/knora-ui-examples/core-demo/lists/lists.component.ts
  yarn.lock
Labels: enhancement

#92 Viewer module: still image representation
  angular.json
  package.json
  projects/knora/action/src/lib/action.module.ts
  projects/knora/authentication/README.md
  projects/knora/core/README.md
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/core/src/lib/declarations/api/shared/date.ts
  projects/knora/core/src/lib/services/v2/ontology-cache.service.ts
  projects/knora/search/src/lib/search.module.ts
  projects/knora/viewer/package.json
  projects/knora/viewer/src/lib/assets/style/viewer.scss
  projects/knora/viewer/src/lib/property/index.ts
  projects/knora/viewer/src/lib/property/integer-value/integer-value.component.ts
  projects/knora/viewer/src/lib/resource/index.ts
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.html
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.scss
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.ts
  projects/knora/viewer/src/lib/view/index.ts
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.html
  projects/knora/viewer/src/lib/viewer.module.ts
  projects/knora/viewer/src/public_api.ts
  src/app/app.config.ts
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/knora-ui-examples/core-demo/resource/resource.component.html
  src/app/knora-ui-examples/core-demo/resource/resource.component.ts
  src/app/knora-ui-examples/viewer-demo/objects/objects.component.spec.ts
  src/app/knora-ui-examples/viewer-demo/objects/objects.component.ts
  src/app/knora-ui-examples/viewer-demo/properties/properties.component.html
  src/app/knora-ui-examples/viewer-demo/properties/properties.component.ts
  src/app/knora-ui-examples/viewer-demo/resources/resources.component.html
  src/app/knora-ui-examples/viewer-demo/resources/resources.component.scss
  src/app/knora-ui-examples/viewer-demo/resources/resources.component.spec.ts
  src/app/knora-ui-examples/viewer-demo/resources/resources.component.ts
  src/app/knora-ui-examples/viewer-demo/views/views.component.html
  src/app/partials/module-index/module-index.component.html
  src/app/partials/module-index/module-index.component.scss
  src/app/partials/module-index/module-index.component.ts
  src/app/partials/pipes/sanitize-html.pipe.ts
  yarn.lock
Labels: feature

#101 Core module: fix month precision date
  projects/knora/core/package.json
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.ts
Labels: bug
