Repository dasch-swiss/knora-ui, pull requests merged in 2018-11, with the labels that each got.

#106 Wip/gnd directive setter getter
  .travis.yml
  projects/knora/action/src/lib/directives/gnd.directive.spec.ts
  projects/knora/action/src/lib/directives/gnd.directive.ts
  projects/knora/core/src/lib/declarations/api/shared/date.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.ts
  projects/knora/viewer/src/lib/property/boolean-value/boolean-value.component.html
  projects/knora/viewer/src/lib/property/boolean-value/boolean-value.component.spec.ts
  projects/knora/viewer/src/lib/property/boolean-value/boolean-value.component.ts
  projects/knora/viewer/src/lib/property/color-value/color-value.component.html
  projects/knora/viewer/src/lib/property/color-value/color-value.component.spec.ts
  projects/knora/viewer/src/lib/property/color-value/color-value.component.ts
  projects/knora/viewer/src/lib/property/date-value/date-value.component.html
  projects/knora/viewer/src/lib/property/date-value/date-value.component.spec.ts
  projects/knora/viewer/src/lib/property/date-value/date-value.component.ts
  projects/knora/viewer/src/lib/property/decimal-value/decimal-value.component.html
  projects/knora/viewer/src/lib/property/decimal-value/decimal-value.component.spec.ts
  projects/knora/viewer/src/lib/property/decimal-value/decimal-value.component.ts
  projects/knora/viewer/src/lib/property/geometry-value/geometry-value.component.html
  projects/knora/viewer/src/lib/property/geometry-value/geometry-value.component.spec.ts
  projects/knora/viewer/src/lib/property/geometry-value/geometry-value.component.ts
  projects/knora/viewer/src/lib/property/geoname-value/geoname-value.component.html
  projects/knora/viewer/src/lib/property/integer-value/integer-value.component.html
  projects/knora/viewer/src/lib/property/integer-value/integer-value.component.spec.ts
  projects/knora/viewer/src/lib/property/integer-value/integer-value.component.ts
  projects/knora/viewer/src/lib/property/interval-value/interval-value.component.html
  projects/knora/viewer/src/lib/property/interval-value/interval-value.component.spec.ts
  projects/knora/viewer/src/lib/property/interval-value/interval-value.component.ts
  projects/knora/viewer/src/lib/property/link-value/link-value.component.html
  projects/knora/viewer/src/lib/property/link-value/link-value.component.ts
  projects/knora/viewer/src/lib/property/list-value/list-value.component.html
  projects/knora/viewer/src/lib/property/list-value/list-value.component.spec.ts
  projects/knora/viewer/src/lib/property/list-value/list-value.component.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-html/text-value-as-html.component.html
  projects/knora/viewer/src/lib/property/text-value/text-value-as-html/text-value-as-html.component.spec.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-html/text-value-as-html.component.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-string/text-value-as-string.component.html
  projects/knora/viewer/src/lib/property/text-value/text-value-as-string/text-value-as-string.component.spec.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-string/text-value-as-string.component.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-xml/text-value-as-xml.component.html
  projects/knora/viewer/src/lib/property/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-xml/text-value-as-xml.component.ts
  projects/knora/viewer/src/lib/property/textfile-value/textfile-value.component.html
  projects/knora/viewer/src/lib/property/textfile-value/textfile-value.component.spec.ts
  projects/knora/viewer/src/lib/property/textfile-value/textfile-value.component.ts
  projects/knora/viewer/src/lib/property/uri-value/uri-value.component.html
  projects/knora/viewer/src/lib/property/uri-value/uri-value.component.spec.ts
  projects/knora/viewer/src/lib/property/uri-value/uri-value.component.ts
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.spec.ts
  src/app/knora-ui-examples/search-demo/search-result/search-result.component.html
  src/app/knora-ui-examples/search-demo/search-result/search-result.component.ts
  src/app/knora-ui-examples/viewer-demo/properties/properties.component.html
  src/app/knora-ui-examples/viewer-demo/properties/properties.component.ts
Labels: enhancement

#104 Tests for ExtendedSearchComponent
  .circleci/config.yml
  .travis.yml
  projects/knora/search/src/lib/extended-search/extended-search.component.html
  projects/knora/search/src/lib/extended-search/extended-search.component.spec.ts
  projects/knora/search/src/lib/extended-search/extended-search.component.ts
  projects/knora/search/src/lib/extended-search/select-ontology/select-ontology.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/boolean-value/boolean-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/date-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/header-calendar/header-calendar.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/decimal-value/decimal-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/integer-value/integer-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/text-value/text-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/uri-value/uri-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-resource-class/select-resource-class.component.spec.ts
  projects/knora/search/src/lib/search.component.spec.ts
Labels: testing

#112 Add tests for ReadPropertyItem classes
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.spec.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.ts
  projects/knora/core/src/lib/declarations/api/v2/still-image/image-region.ts
  projects/knora/core/src/lib/declarations/api/v2/still-image/point-2d.ts
  projects/knora/core/src/lib/declarations/api/v2/still-image/read-geom-value.ts
  projects/knora/core/src/lib/declarations/api/v2/still-image/read-still-image-file-value.ts
  projects/knora/core/src/lib/declarations/api/v2/still-image/region-geometry.ts
  src/app/knora-ui-examples/core-demo/resource/resource.component.ts
Labels: testing

#111 fix (core): remove redundant export statements
  projects/knora/core/src/lib/declarations/api/v2/json-ld/graph.ts
  projects/knora/core/src/lib/declarations/api/v2/json-ld/json-ld.ts
  projects/knora/core/src/lib/declarations/index.ts
  projects/knora/core/src/lib/services/index.ts
Labels: bug

#123 Fix/date component template
  projects/knora/viewer/src/lib/property/date-value/date-value.component.html
  projects/knora/viewer/src/lib/property/date-value/date-value.component.spec.ts
  projects/knora/viewer/src/lib/property/date-value/date-value.component.ts
Labels: enhancement

#87 Core module: update textValueHasMapping
  README.md
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.spec.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.ts
  projects/knora/core/src/lib/services/v2/convert-jsonld.spec.ts
  projects/knora/core/src/lib/services/v2/convert-jsonld.ts
  projects/knora/core/src/lib/services/v2/ontology-cache.service.spec.ts
  projects/knora/core/src/lib/test-data/ontologycache/anything-complex-onto.json
  projects/knora/core/src/lib/test-data/ontologycache/beol-complex-onto.json
  projects/knora/core/src/lib/test-data/ontologycache/knora-api-complex-onto.json
  projects/knora/core/src/lib/test-data/ontologycache/ontology-metadata.json
  projects/knora/core/src/lib/test-data/ontologycache/something-complex-onto.json
  projects/knora/core/src/lib/test-data/resources/PageWithImages.json
  projects/knora/core/src/lib/test-data/resources/SearchForHolzschnitt.json
  projects/knora/core/src/lib/test-data/resources/Testthing.json
  projects/knora/core/src/lib/test-data/resources/TextfileRepresentation.json
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.spec.ts
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.ts
Labels: enhancement
