Repository dasch-swiss/knora-ui, pull requests merged in 2019-04, with the labels that each got.

#204 style(viewer): search results list
  projects/knora/viewer/src/lib/view/list-view/list-view.component.html
  projects/knora/viewer/src/lib/view/list-view/list-view.component.scss
Labels: styling

#197 feat(action): Add message component
  docs/app/app.config.ts
  docs/app/app.module.ts
  docs/app/app.routing.ts
  docs/app/knora-ui-examples/action-demo/action-demo.component.html
  docs/app/knora-ui-examples/action-demo/message/message.component.html
  docs/app/knora-ui-examples/action-demo/message/message.component.scss
  docs/app/knora-ui-examples/action-demo/message/message.component.spec.ts
  docs/app/knora-ui-examples/action-demo/message/message.component.ts
  docs/data/documentation/action/admin-image.json
  docs/data/documentation/action/message.json
  docs/data/documentation/action/sort-button.json
  docs/data/documentation/authentication/readme.md
  docs/data/documentation/search/readme.md
  docs/data/documentation/viewer/grid-view.json
  docs/data/documentation/viewer/list-view.json
  docs/data/documentation/viewer/readme.md
  docs/data/documentation/viewer/resource-view.json
  docs/data/documentation/viewer/search-results.json
  docs/main.js
  docs/main.js.map
  projects/knora/action/src/assets/i18n/statusMsg.json
  projects/knora/action/src/lib/action.module.ts
  projects/knora/action/src/lib/message/message.component.html
  projects/knora/action/src/lib/message/message.component.scss
  projects/knora/action/src/lib/message/message.component.spec.ts
  projects/knora/action/src/lib/message/message.component.ts
  projects/knora/action/src/lib/sort-button/sort-button.component.html
  projects/knora/action/src/lib/sort-button/sort-button.component.spec.ts
  projects/knora/action/src/lib/sort-button/sort-button.component.ts
  projects/knora/action/src/public_api.ts
  projects/knora/action/src/typings.d.ts
  projects/knora/action/tsconfig.lib.json
  src/app/app.config.ts
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/knora-ui-examples/action-demo/action-demo.component.html
  src/app/knora-ui-examples/action-demo/message/message.component.html
  src/app/knora-ui-examples/action-demo/message/message.component.scss
  src/app/knora-ui-examples/action-demo/message/message.component.spec.ts
  src/app/knora-ui-examples/action-demo/message/message.component.ts
  src/data/documentation/action/admin-image.json
  src/data/documentation/action/message.json
  src/data/documentation/action/sort-button.json
  src/data/documentation/authentication/readme.md
  src/data/documentation/search/readme.md
  src/data/documentation/viewer/grid-view.json
  src/data/documentation/viewer/list-view.json
  src/data/documentation/viewer/readme.md
  src/data/documentation/viewer/resource-view.json
  src/data/documentation/viewer/search-results.json
Labels: feature

#205 feat(core): implement resource gui-order
  docs/app/knora-ui-examples/core-demo/resource/resource.component.html
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/core/src/lib/declarations/api/v2/moving-image/moving-image-representation.ts
  projects/knora/core/src/lib/declarations/api/v2/moving-image/moving-image-sequence.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.spec.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.ts
  projects/knora/core/src/lib/declarations/api/v2/resources/read-resource.ts
  projects/knora/core/src/lib/services/v2/convert-jsonld.ts
  projects/knora/core/src/lib/services/v2/ontology-cache.service.spec.ts
  projects/knora/core/src/lib/services/v2/ontology-cache.service.ts
  projects/knora/search/src/lib/extended-search/extended-search.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-resource-class/select-resource-class.component.spec.ts
  projects/knora/search/src/lib/search.module.ts
  projects/knora/viewer/src/lib/property/link-value/link-value.component.spec.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-html/text-value-as-html.component.spec.ts
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.html
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.html
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.ts
  projects/knora/viewer/src/lib/view/list-view/list-view.component.html
  projects/knora/viewer/src/lib/view/list-view/list-view.component.ts
  projects/knora/viewer/src/lib/view/properties-view/properties-view.component.ts
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.html
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.scss
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
  src/app/app.module.ts
Labels: breaking, feature

#206 feat(authentication): store info about project admin
  projects/knora/authentication/src/lib/declarations/current-user.ts
  projects/knora/authentication/src/lib/declarations/index.ts
  projects/knora/authentication/src/lib/declarations/session.ts
  projects/knora/authentication/src/lib/session/session.service.ts
  projects/knora/authentication/src/public_api.ts
  projects/knora/core/src/lib/declarations/api/admin/users/user.ts
  projects/knora/core/src/lib/declarations/index.ts
  projects/knora/core/src/lib/services/api.service.ts
Labels: feature

#207 feat: Update version
  docs/app/app.module.ts
  docs/app/knora-ui-examples/authentication-demo/auth/auth.component.ts
  docs/app/knora-ui-examples/core-demo/resource/resource.component.html
  docs/data/documentation/action/message.json
  docs/data/documentation/authentication/readme.md
  docs/data/documentation/authentication/session.json
  docs/data/documentation/core/api.json
  docs/data/documentation/core/convert-jsonld.json
  docs/data/documentation/core/ontology-cache.json
  docs/data/documentation/search/fulltext-search.json
  docs/data/documentation/search/readme.md
  docs/data/documentation/search/search-panel.json
  docs/data/documentation/viewer/grid-view.json
  docs/data/documentation/viewer/list-view.json
  docs/data/documentation/viewer/properties-view.json
  docs/data/documentation/viewer/readme.md
  docs/data/documentation/viewer/resource-view.json
  docs/data/documentation/viewer/search-results.json
  docs/main.js
  docs/main.js.map
  projects/knora/action/package.json
  projects/knora/authentication/README.md
  projects/knora/authentication/package.json
  projects/knora/core/package.json
  projects/knora/search/README.md
  projects/knora/search/package.json
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.ts
  projects/knora/viewer/README.md
  projects/knora/viewer/package.json
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
  src/app/knora-ui-examples/authentication-demo/auth/auth.component.ts
  src/data/documentation/action/message.json
  src/data/documentation/authentication/readme.md
  src/data/documentation/authentication/session.json
  src/data/documentation/core/api.json
  src/data/documentation/core/convert-jsonld.json
  src/data/documentation/core/ontology-cache.json
  src/data/documentation/search/fulltext-search.json
  src/data/documentation/search/readme.md
  src/data/documentation/search/search-panel.json
  src/data/documentation/viewer/grid-view.json
  src/data/documentation/viewer/list-view.json
  src/data/documentation/viewer/properties-view.json
  src/data/documentation/viewer/readme.md
  src/data/documentation/viewer/resource-view.json
  src/data/documentation/viewer/search-results.json
Labels: documentation, feature

#208 feature (viewer): slice long texts of any kind of search results
  projects/knora/viewer/src/lib/view/list-view/list-view.component.html
Labels: enhancement

#213 chore (package.json): remove angular/http package
  package.json
  yarn.lock
Labels: refactor

#209 style(action): refactor some style issues in action module
  projects/knora/action/src/lib/message/message.component.scss
  projects/knora/action/src/lib/sort-button/sort-button.component.html
  projects/knora/action/src/lib/sort-button/sort-button.component.scss
  projects/knora/action/src/lib/sort-button/sort-button.component.spec.ts
  projects/knora/action/src/lib/sort-button/sort-button.component.ts
  projects/knora/authentication/src/lib/authentication.service.ts
Labels: styling

#211 docs (@knora/viewer): add viewer docs
  docs/app/app.config.ts
  docs/app/app.module.ts
  docs/app/app.routing.ts
  docs/app/knora-ui-examples/viewer-demo/search-results/search-results.component.html
  docs/app/knora-ui-examples/viewer-demo/search-results/search-results.component.scss
  docs/app/knora-ui-examples/viewer-demo/search-results/search-results.component.spec.ts
  docs/app/knora-ui-examples/viewer-demo/search-results/search-results.component.ts
  docs/app/partials/documentation-viewer/documentation-viewer.component.ts
  docs/data/documentation/action/sort-button.json
  docs/data/documentation/authentication/authentication.json
  docs/data/documentation/viewer/grid-view.json
  docs/data/documentation/viewer/list-view.json
  docs/data/documentation/viewer/resource-view.json
  docs/data/documentation/viewer/search-results-by-project-example.png
  docs/data/documentation/viewer/search-results-with-mode-and-params-example.png
  docs/data/documentation/viewer/search-results.json
  docs/data/documentation/viewer/simple-search-results-example.png
  docs/main.js
  docs/main.js.map
  projects/knora/action/src/lib/sort-button/sort-button.component.ts
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.ts
  projects/knora/viewer/src/lib/view/list-view/list-view.component.ts
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
  src/app/app.config.ts
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/knora-ui-examples/viewer-demo/search-results/search-results.component.html
  src/app/knora-ui-examples/viewer-demo/search-results/search-results.component.scss
  src/app/knora-ui-examples/viewer-demo/search-results/search-results.component.spec.ts
  src/app/knora-ui-examples/viewer-demo/search-results/search-results.component.ts
  src/app/partials/documentation-viewer/documentation-viewer.component.ts
  src/data/documentation/action/sort-button.json
  src/data/documentation/authentication/authentication.json
  src/data/documentation/viewer/grid-view.json
  src/data/documentation/viewer/list-view.json
  src/data/documentation/viewer/resource-view.json
  src/data/documentation/viewer/search-results-by-project-example.png
  src/data/documentation/viewer/search-results-with-mode-and-params-example.png
  src/data/documentation/viewer/search-results.json
  src/data/documentation/viewer/simple-search-results-example.png
Labels: documentation

#215 feature (viewer): implement guiOrder
  docs/data/documentation/authentication/readme.md
  docs/data/documentation/core/ontology-cache.json
  docs/data/documentation/search/readme.md
  docs/data/documentation/viewer/readme.md
  docs/data/documentation/viewer/resource-view.json
  docs/main.js
  docs/main.js.map
  docs/polyfills.js
  docs/styles.js
  docs/styles.js.map
  projects/knora/action/package.json
  projects/knora/authentication/README.md
  projects/knora/authentication/package.json
  projects/knora/core/package.json
  projects/knora/core/src/lib/services/v2/ontology-cache.service.ts
  projects/knora/search/README.md
  projects/knora/search/package.json
  projects/knora/viewer/README.md
  projects/knora/viewer/package.json
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.html
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.scss
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.ts
  src/data/documentation/authentication/readme.md
  src/data/documentation/core/ontology-cache.json
  src/data/documentation/search/readme.md
  src/data/documentation/viewer/readme.md
  src/data/documentation/viewer/resource-view.json
Labels: enhancement

#217 style(search/action): fix styling issues and bug fixes
  projects/knora/action/src/lib/message/message.component.scss
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.html
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.scss
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.ts
  projects/knora/search/src/lib/search.component.scss
  projects/knora/viewer/src/lib/view/list-view/list-view.component.scss
  projects/knora/viewer/src/lib/view/list-view/list-view.component.ts
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
Labels: styling

#219 feat(search): improve extended search
  projects/knora/search/src/lib/extended-search/extended-search.component.html
  projects/knora/search/src/lib/extended-search/extended-search.component.scss
  projects/knora/search/src/lib/extended-search/extended-search.component.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
Labels: enhancement, feature

#220 docs: update docs
  README.md
  docs/data/documentation/authentication/readme.md
  docs/data/documentation/demo/readme.md
  docs/data/documentation/search/extended-search.json
  docs/data/documentation/search/fulltext-search.json
  docs/data/documentation/search/readme.md
  docs/data/documentation/viewer/readme.md
  docs/data/documentation/viewer/resource-view.json
  docs/data/documentation/viewer/search-results.json
  docs/main.js
  docs/main.js.map
  projects/knora/action/package.json
  projects/knora/authentication/README.md
  projects/knora/authentication/package.json
  projects/knora/core/package.json
  projects/knora/search/README.md
  projects/knora/search/package.json
  projects/knora/search/src/lib/extended-search/extended-search.component.ts
  projects/knora/viewer/README.md
  projects/knora/viewer/package.json
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
  src/data/documentation/authentication/readme.md
  src/data/documentation/demo/readme.md
  src/data/documentation/search/extended-search.json
  src/data/documentation/search/fulltext-search.json
  src/data/documentation/search/readme.md
  src/data/documentation/viewer/readme.md
  src/data/documentation/viewer/resource-view.json
  src/data/documentation/viewer/search-results.json
Labels: documentation
