Repository dasch-swiss/knora-ui, pull requests merged in 2019-03, with the labels that each got.

#189 Update Angular 7
  README.md
  package.json
  projects/knora/action/README.md
  projects/knora/action/package.json
  projects/knora/action/src/lib/progress-indicator/progress-indicator.component.spec.ts
  projects/knora/authentication/README.md
  projects/knora/authentication/package.json
  projects/knora/authentication/src/lib/login-form/login-form.component.spec.ts
  projects/knora/core/README.md
  projects/knora/core/package.json
  projects/knora/search/README.md
  projects/knora/search/package.json
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/header-calendar/header-calendar.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/header-calendar/header-calendar.component.ts
  projects/knora/viewer/README.md
  projects/knora/viewer/package.json
  projects/knora/viewer/src/lib/property/boolean-value/boolean-value.component.spec.ts
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/playground/authentication-pg/authentication-pg.component.html
  src/app/playground/authentication-pg/authentication-pg.component.scss
  src/app/playground/authentication-pg/authentication-pg.component.spec.ts
  src/app/playground/authentication-pg/authentication-pg.component.ts
  src/app/playground/ontology-pg/ontology-pg.component.html
  src/app/playground/ontology-pg/ontology-pg.component.scss
  src/app/playground/ontology-pg/ontology-pg.component.spec.ts
  src/app/playground/ontology-pg/ontology-pg.component.ts
  src/app/playground/playground.component.html
  src/app/playground/playground.component.scss
  src/app/playground/playground.component.spec.ts
  src/app/playground/playground.component.ts
  src/app/playground/search-pg/search-pg.component.html
  src/app/playground/search-pg/search-pg.component.scss
  src/app/playground/search-pg/search-pg.component.spec.ts
  src/app/playground/search-pg/search-pg.component.ts
  src/app/playground/search-pg/search-result/search-result.component.html
  src/app/playground/search-pg/search-result/search-result.component.scss
  src/app/playground/search-pg/search-result/search-result.component.spec.ts
  src/app/playground/search-pg/search-result/search-result.component.ts
  src/app/playground/viewer-pg/viewer-pg.component.html
  src/app/playground/viewer-pg/viewer-pg.component.scss
  src/app/playground/viewer-pg/viewer-pg.component.spec.ts
  src/app/playground/viewer-pg/viewer-pg.component.ts
  src/polyfills.ts
  tsconfig.json
  yarn.lock
Labels: breaking, enhancement

#192 docs: update documentation
  README.md
  docs/data/documentation/demo/readme.md
  src/data/documentation/demo/readme.md
  update_docs.sh
Labels: documentation

#195 feat(search): Filter by project in full-text search
  package.json
  projects/knora/core/src/lib/core.module.ts
  projects/knora/search/package.json
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.html
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.scss
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.spec.ts
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.spec.ts
  projects/knora/search/src/lib/search.module.ts
  projects/knora/viewer/package.json
  projects/knora/viewer/src/lib/view/graph-view/graph-view.component.html
  projects/knora/viewer/src/lib/view/kui-view.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.scss
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
Labels: feature

#203 Feat(viewer): configure search results
  projects/knora/action/package.json
  projects/knora/authentication/README.md
  projects/knora/authentication/package.json
  projects/knora/core/package.json
  projects/knora/search/README.md
  projects/knora/search/package.json
  projects/knora/viewer/README.md
  projects/knora/viewer/package.json
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.html
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.spec.ts
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.ts
  projects/knora/viewer/src/lib/view/list-view/list-view.component.html
  projects/knora/viewer/src/lib/view/list-view/list-view.component.spec.ts
  projects/knora/viewer/src/lib/view/list-view/list-view.component.ts
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
  projects/knora/viewer/src/lib/viewer.module.ts
Labels: feature

#202 style(action): get bigger gravatar profile picture
  projects/knora/action/src/lib/admin-image/admin-image.directive.spec.ts
  projects/knora/action/src/lib/admin-image/admin-image.directive.ts
Labels: styling
