Repository dasch-swiss/knora-ui, pull requests merged in 2019-11, with the labels that each got.

#355 New method to delete and erase resource
  projects/knora/core/src/lib/services/v2/resource.service.ts
  projects/knora/viewer/src/lib/viewer.module.ts
Labels: enhancement, stage/code-review

#364 Upgrade the package karma-jasmine
  package.json
  projects/knora/action/src/lib/jdn-datepicker/jdn-datepicker.directive.spec.ts
  yarn.lock
Labels: testing

#362 Incoming service: fix tests
  projects/knora/core/src/lib/services/v2/incoming.service.spec.ts
Labels: testing

#367 Edit main README file
  README.md
Labels: documentation, enhancement, refactor

#368 Start to fix broken tests
  .circleci/config.yml
  .travis.yml
  projects/knora/action/src/lib/login-form/login-form.component.spec.ts
  projects/knora/action/src/lib/login-form/login-form.component.ts
Labels: refactor

#369 Fix tests in @knora/core
  .circleci/config.yml
  .travis.yml
  package.json
  projects/knora/core/src/lib/services/admin/groups.service.spec.ts
  projects/knora/core/src/lib/services/admin/lists.service.spec.ts
  projects/knora/core/src/lib/services/admin/projects.service.spec.ts
  projects/knora/core/src/lib/services/admin/status-msg.service.spec.ts
  projects/knora/core/src/lib/services/admin/users.service.spec.ts
  projects/knora/core/src/lib/services/api.service.spec.ts
  projects/knora/core/src/lib/services/index.ts
  projects/knora/core/src/lib/services/v2/basic-ontology.service.spec.ts
  projects/knora/core/src/lib/services/v2/basic-ontology.service.ts
  projects/knora/core/src/lib/services/v2/incoming.service.spec.ts
  projects/knora/core/src/lib/services/v2/list-cache.service.spec.ts
  projects/knora/core/src/lib/services/v2/list.service.spec.ts
  projects/knora/core/src/lib/services/v2/ontology-cache.service.spec.ts
  projects/knora/core/src/lib/services/v2/ontology.service.spec.ts
  projects/knora/core/src/lib/services/v2/resource-types.service.spec.ts
  projects/knora/core/src/lib/services/v2/resource.service.spec.ts
  projects/knora/core/src/lib/services/v2/search-params.service.spec.ts
  projects/knora/core/src/lib/services/v2/search.service.spec.ts
  projects/knora/core/src/lib/services/v2/store.service.spec.ts
  projects/knora/core/src/lib/session.service.spec.ts
  yarn.lock
Labels: testing
