Repository dasch-swiss/knora-ui, pull requests merged in 2019-08, with the labels that each got.

#266 style: Improve responsive design for phone
  package.json
  projects/knora/action/src/assets/style/_responsive.scss
  projects/knora/action/src/lib/message/message.component.scss
  projects/knora/search/src/lib/assets/style/_responsive.scss
  projects/knora/search/src/lib/assets/style/search.scss
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.html
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.scss
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.html
  projects/knora/search/src/lib/search-panel/search-panel.component.scss
  projects/knora/search/src/lib/search-panel/search-panel.component.ts
  projects/knora/viewer/src/lib/assets/style/_responsive.scss
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.scss
Labels: enhancement, styling

#272 feat(authentication): Login form with email or username
  projects/knora/authentication/src/lib/authentication.service.ts
  projects/knora/authentication/src/lib/login-form/login-form.component.html
  projects/knora/authentication/src/lib/login-form/login-form.component.ts
  projects/knora/authentication/src/lib/session/session.service.ts
  projects/knora/core/src/lib/services/admin/users.service.ts
Labels: enhancement

#287 Support https in gravatar service
  projects/knora/action/ng-package.json
  projects/knora/action/ng-package.prod.json
  projects/knora/action/src/lib/admin-image/admin-image.directive.ts
Labels: bug
