Repository dasch-swiss/knora-ui, pull requests merged in 2019-05, with the labels that each got.

#222 feat(search): Implement the expert search
  projects/knora/search/src/lib/expert-search/expert-search.component.html
  projects/knora/search/src/lib/expert-search/expert-search.component.scss
  projects/knora/search/src/lib/expert-search/expert-search.component.spec.ts
  projects/knora/search/src/lib/expert-search/expert-search.component.ts
  projects/knora/search/src/lib/extended-search/extended-search.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.spec.ts
  projects/knora/search/src/lib/search.module.ts
  projects/knora/search/src/public_api.ts
Labels: enhancement, feature

#224 test(search): Remove fdescribe
  projects/knora/search/src/lib/expert-search/expert-search.component.spec.ts
Labels: testing

#226 fix(app): Update jquery version
  yarn.lock
Labels: warning

#225 feat(view/action): Show no-results message
  projects/knora/action/src/assets/i18n/statusMsg.json
  projects/knora/action/src/assets/i18n/statusMsg.ts
  projects/knora/action/src/lib/action.module.ts
  projects/knora/action/src/lib/message/message.component.html
  projects/knora/action/src/lib/message/message.component.spec.ts
  projects/knora/action/src/lib/message/message.component.ts
  projects/knora/action/src/typings.d.ts
  projects/knora/action/tsconfig.lib.json
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.spec.ts
  projects/knora/viewer/tsconfig.lib.json
  tsconfig.json
Labels: enhancement, styling

#170 Get lists from Knora
  angular.json
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/core/src/lib/declarations/api/operators.ts
  projects/knora/core/src/lib/services/index.ts
  projects/knora/core/src/lib/services/v2/grav-search.service.spec.ts
  projects/knora/core/src/lib/services/v2/grav-search.service.ts
  projects/knora/core/src/lib/services/v2/list-cache.service.spec.ts
  projects/knora/core/src/lib/services/v2/list-cache.service.ts
  projects/knora/core/src/lib/services/v2/list.service.spec.ts
  projects/knora/core/src/lib/services/v2/list.service.ts
  projects/knora/core/src/lib/services/v2/ontology-cache.service.spec.ts
  projects/knora/core/src/lib/services/v2/ontology-cache.service.ts
  projects/knora/core/src/lib/test-data/list/treeList-expanded.json
  projects/knora/core/src/lib/test-data/list/treeList.json
  projects/knora/core/src/lib/test-data/list/treeListNode-expanded.json
  projects/knora/core/src/lib/test-data/list/treeListNode.json
  projects/knora/search/src/lib/extended-search/extended-search.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/date-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/date-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-display/list-display.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-display/list-display.component.scss
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-display/list-display.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-display/list-display.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-value.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-value.component.scss
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.spec.ts
  projects/knora/search/src/lib/search.component.spec.ts
  projects/knora/search/src/lib/search.module.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.spec.ts
  src/app/app.module.ts
  src/app/app.routing.ts
Labels: enhancement, feature, refactor

#231 Fix gravsearch
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/core/src/lib/services/v2/grav-search.service.spec.ts
  projects/knora/core/src/lib/services/v2/grav-search.service.ts
Labels: bug

#232 Add Tests for Gravsearch Service
  projects/knora/core/src/lib/services/v2/grav-search.service.spec.ts
Labels: testing

#233 Display List Value: Query list node from ListCacheService
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.spec.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.ts
  projects/knora/core/src/lib/services/v2/convert-jsonld.spec.ts
  projects/knora/core/src/lib/services/v2/convert-jsonld.ts
  projects/knora/core/src/lib/services/v2/ontology-cache.service.spec.ts
  projects/knora/core/src/lib/test-data/ontologycache/knora-api-complex-onto.json
  projects/knora/core/src/lib/test-data/resources/EulerLetter_176-O.json
  projects/knora/core/src/lib/test-data/resources/Testthing.json
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.spec.ts
  projects/knora/viewer/src/lib/property/list-value/list-value.component.html
  projects/knora/viewer/src/lib/property/list-value/list-value.component.spec.ts
  projects/knora/viewer/src/lib/property/list-value/list-value.component.ts
Labels: feature
