Repository dasch-swiss/knora-ui, pull requests merged in 2019-09, with the labels that each got.

#311 Update configuration for github release notes
  .grenrc.js
  README.md
  projects/knora/core/src/lib/declarations/api/admin/lists/list-node-update-payload.ts
Labels: chore

#315 Input / textarea for StringLiteral
  package.json
  projects/knora/action/README.md
  projects/knora/action/src/assets/style/action.scss
  projects/knora/action/src/lib/action.module.ts
  projects/knora/action/src/lib/sort-button/sort-button.component.ts
  projects/knora/action/src/lib/string-literal-input/string-literal-input.component.html
  projects/knora/action/src/lib/string-literal-input/string-literal-input.component.scss
  projects/knora/action/src/lib/string-literal-input/string-literal-input.component.spec.ts
  projects/knora/action/src/lib/string-literal-input/string-literal-input.component.ts
  projects/knora/action/src/public_api.ts
Labels: enhancement

#316 chore: Update gren info
  .grenrc.js
  CHANGELOG.md
Labels: chore

#318 Improvements on the StringLiteral Input
  projects/knora/action/src/assets/style/action.scss
  projects/knora/action/src/lib/action.module.ts
  projects/knora/action/src/lib/pipes/stringify-string-literal.pipe.spec.ts
  projects/knora/action/src/lib/pipes/stringify-string-literal.pipe.ts
  projects/knora/action/src/lib/string-literal-input/string-literal-input.component.html
  projects/knora/action/src/lib/string-literal-input/string-literal-input.component.ts
  projects/knora/action/src/public_api.ts
  projects/knora/core/src/lib/services/admin/lists.service.ts
Labels: enhancement, stage/in-progress

#325 Enhancement on login / logout process and resource viewer
  .circleci/config.yml
  .travis.yml
  projects/knora/action/src/lib/message/message.component.html
  projects/knora/action/src/lib/sort-button/sort-button.component.spec.ts
  projects/knora/authentication/src/lib/authentication.service.spec.ts
  projects/knora/authentication/src/lib/authentication.service.ts
  projects/knora/authentication/src/lib/guard/auth.guard.spec.ts
  projects/knora/authentication/src/lib/login-form/login-form.component.html
  projects/knora/authentication/src/lib/login-form/login-form.component.scss
  projects/knora/authentication/src/lib/login-form/login-form.component.spec.ts
  projects/knora/authentication/src/lib/login-form/login-form.component.ts
  projects/knora/authentication/src/lib/session/session.service.spec.ts
  projects/knora/authentication/src/lib/session/session.service.ts
  projects/knora/core/src/lib/declarations/api/admin/authentication/authentication-request-payload.ts
  projects/knora/core/src/lib/declarations/api/admin/authentication/logout-response.ts
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/core/src/lib/declarations/api/v2/moving-image/moving-image-representation.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.ts
  projects/knora/core/src/lib/declarations/api/v2/representations/audio-representation.ts
  projects/knora/core/src/lib/declarations/api/v2/representations/fileRepresentation.ts
  projects/knora/core/src/lib/declarations/api/v2/representations/moving-image-representation.ts
  projects/knora/core/src/lib/declarations/api/v2/representations/region.ts
  projects/knora/core/src/lib/declarations/api/v2/representations/sequence.ts
  projects/knora/core/src/lib/declarations/api/v2/representations/still-image-representation.ts
  projects/knora/core/src/lib/declarations/api/v2/resources/read-resource.ts
  projects/knora/core/src/lib/declarations/api/v2/resources/read-resources-sequence.ts
  projects/knora/core/src/lib/declarations/api/v2/still-image/image-region.ts
  projects/knora/core/src/lib/declarations/api/v2/still-image/still-image-representation.ts
  projects/knora/core/src/lib/declarations/index.ts
  projects/knora/core/src/lib/services/api.service.ts
  projects/knora/core/src/lib/services/v2/convert-jsonld.ts
  projects/knora/core/src/lib/services/v2/incoming.service.ts
  projects/knora/core/src/lib/services/v2/ontology.service.ts
  projects/knora/core/src/lib/services/v2/resource.service.spec.ts
  projects/knora/core/src/lib/services/v2/resource.service.ts
  projects/knora/core/src/lib/services/v2/search.service.ts
  projects/knora/viewer/src/lib/assets/style/viewer.scss
  projects/knora/viewer/src/lib/property/link-value/link-value.component.html
  projects/knora/viewer/src/lib/property/link-value/link-value.component.spec.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-html/text-value-as-html.component.spec.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-string/text-value-as-string.component.html
  projects/knora/viewer/src/lib/property/text-value/text-value-as-string/text-value-as-string.component.scss
  projects/knora/viewer/src/lib/property/text-value/text-value-as-string/text-value-as-string.component.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
  projects/knora/viewer/src/lib/property/uri-value/uri-value.component.html
  projects/knora/viewer/src/lib/resource/moving-image/moving-image.component.html
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.html
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.spec.ts
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.ts
  projects/knora/viewer/src/lib/view/kui-view.ts
  projects/knora/viewer/src/lib/view/properties-view/properties-view.component.html
  projects/knora/viewer/src/lib/view/properties-view/properties-view.component.scss
  projects/knora/viewer/src/lib/view/properties-view/properties-view.component.spec.ts
  projects/knora/viewer/src/lib/view/properties-view/properties-view.component.ts
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.html
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.scss
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.ts
  tslint.json
Labels: breaking/api, bug, enhancement, refactor

#328 Search panel improvements
  package.json
  projects/knora/search/README.md
  projects/knora/search/src/assets/images/filter.svg
  projects/knora/search/src/assets/style/_mixins.scss
  projects/knora/search/src/assets/style/_responsive.scss
  projects/knora/search/src/assets/style/search.scss
  projects/knora/search/src/lib/expert-search/expert-search.component.ts
  projects/knora/search/src/lib/extended-search/extended-search.component.ts
  projects/knora/search/src/lib/extended-search/select-ontology/select-ontology.component.ts
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/date-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/decimal-value/decimal-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/integer-value/integer-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/text-value/text-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/uri-value/uri-value.component.ts
  projects/knora/search/src/lib/extended-search/select-resource-class/select-resource-class.component.ts
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.html
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.scss
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.html
  projects/knora/search/src/lib/search-panel/search-panel.component.scss
  projects/knora/search/src/lib/search-panel/search-panel.component.ts
  projects/knora/search/src/lib/search.component.ts
Labels: enhancement, styling

#332 authentication: Using jwt interceptor the right way
  projects/knora/authentication/src/lib/authentication.module.ts
  projects/knora/authentication/src/lib/authentication.service.ts
  projects/knora/authentication/src/lib/interceptors/error.interceptor.ts
  projects/knora/authentication/src/lib/interceptors/index.ts
  projects/knora/authentication/src/lib/interceptors/jwt.interceptor.ts
  projects/knora/authentication/src/lib/interceptors/with-credentials.interceptor.ts
  projects/knora/authentication/src/lib/login-form/login-form.component.ts
  projects/knora/authentication/src/lib/session/session.service.ts
  projects/knora/authentication/src/public_api.ts
Labels: bug, stage/code-review
