Repository dasch-swiss/knora-ui, pull requests merged in 2019-01, with the labels that each got.

#147 Playgrounds
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/playground/playground.component.html
  src/app/playground/playground.component.scss
  src/app/playground/playground.component.spec.ts
  src/app/playground/playground.component.ts
  src/app/playground/search-pg/search-pg.component.html
  src/app/playground/search-pg/search-pg.component.scss
  src/app/playground/search-pg/search-pg.component.spec.ts
  src/app/playground/search-pg/search-pg.component.ts
  src/app/playground/viewer-pg/viewer-pg.component.html
  src/app/playground/viewer-pg/viewer-pg.component.scss
  src/app/playground/viewer-pg/viewer-pg.component.spec.ts
  src/app/playground/viewer-pg/viewer-pg.component.ts
Labels: feature

#141 refactor (core): handle JSONLD conversion in ResourceService
  projects/knora/action/package.json
  projects/knora/core/src/lib/declarations/api/v2/count-query/count-query-result.ts
  projects/knora/core/src/lib/declarations/api/v2/properties/read-property-item.ts
  projects/knora/core/src/lib/declarations/api/v2/resources/read-resource.ts
  projects/knora/core/src/lib/declarations/api/v2/resources/read-resources-sequence.ts
  projects/knora/core/src/lib/declarations/index.ts
  projects/knora/core/src/lib/services/api.service.ts
  projects/knora/core/src/lib/services/v2/convert-jsonld.spec.ts
  projects/knora/core/src/lib/services/v2/convert-jsonld.ts
  projects/knora/core/src/lib/services/v2/incoming.service.spec.ts
  projects/knora/core/src/lib/services/v2/incoming.service.ts
  projects/knora/core/src/lib/services/v2/ontology.service.ts
  projects/knora/core/src/lib/services/v2/resource.service.spec.ts
  projects/knora/core/src/lib/services/v2/resource.service.ts
  projects/knora/core/src/lib/services/v2/search.service.spec.ts
  projects/knora/core/src/lib/services/v2/search.service.ts
  projects/knora/core/src/lib/test-data/ontologyinformation/thing-properties.json
  projects/knora/core/src/lib/test-data/ontologyinformation/thing-resource-classes.json
  projects/knora/core/src/lib/test-data/resources/countQueryResult.json
Labels: enhancement, refactor, warning

#150 Remove old test data
  test-data-depr/basic-ontology.ts
  test-data-depr/ontologycache/beol-complex-onto.json
  test-data-depr/ontologycache/knora-api-complex-onto.json
  test-data-depr/resources/BookWithIncomingPages.json
  test-data-depr/resources/BookWithIncomingPages2.json
  test-data-depr/resources/EulerLetter_176-O.json
  test-data-depr/resources/SearchResultEuler.json
  test-data-depr/resources/Testthing.json
  test-data-depr/shared-test-data.ts
Labels: enhancement

#153 @knora/core: sort by label in asc or desc order
  projects/knora/core/package.json
  projects/knora/core/src/lib/services/v2/ontology-cache.service.spec.ts
  projects/knora/core/src/lib/services/v2/ontology-cache.service.ts
Labels: enhancement

#157 @knora/viewer: list view
  projects/knora/viewer/src/lib/assets/style/viewer.scss
  projects/knora/viewer/src/lib/view/index.ts
  projects/knora/viewer/src/lib/view/kui-view.ts
  projects/knora/viewer/src/lib/view/list-view/list-view.component.html
  projects/knora/viewer/src/lib/view/list-view/list-view.component.scss
  projects/knora/viewer/src/lib/view/list-view/list-view.component.spec.ts
  projects/knora/viewer/src/lib/view/list-view/list-view.component.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.scss
  projects/knora/viewer/src/lib/view/search-results/search-results.component.spec.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
  projects/knora/viewer/src/lib/viewer.module.ts
  src/app/app.routing.ts
Labels: enhancement

#160 @knora/core: Method to create ontology
  projects/knora/core/package.json
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/core/src/lib/declarations/api/v2/ontology/new-ontology.ts
  projects/knora/core/src/lib/declarations/index.ts
  projects/knora/core/src/lib/services/v2/ontology.service.spec.ts
  projects/knora/core/src/lib/services/v2/ontology.service.ts
  projects/knora/core/src/lib/test-data/ontology/new-ontology.json
  projects/knora/core/src/lib/test-data/ontologycache/something-ontology-metadata.json
  src/app/app.module.ts
  src/app/app.routing.ts
  src/app/partials/documentation-viewer/documentation-viewer.component.html
  src/app/playground/authentication-pg/authentication-pg.component.html
  src/app/playground/authentication-pg/authentication-pg.component.scss
  src/app/playground/authentication-pg/authentication-pg.component.spec.ts
  src/app/playground/authentication-pg/authentication-pg.component.ts
  src/app/playground/ontology-pg/ontology-pg.component.html
  src/app/playground/ontology-pg/ontology-pg.component.scss
  src/app/playground/ontology-pg/ontology-pg.component.spec.ts
  src/app/playground/ontology-pg/ontology-pg.component.ts
  src/app/playground/playground.component.html
Labels: feature
