Repository dasch-swiss/knora-ui, pull requests merged in 2019-02, with the labels that each got.

#166 OntoloyCacheService: prevent error when accessing id on undefined
  projects/knora/core/src/lib/services/v2/ontology-cache.service.ts
Labels: bug

#169 Fix search-bar position
  projects/knora/search/package.json
  projects/knora/search/src/lib/search.component.scss
Labels: styling

#171 feature (core): load config at runtime
  README.md
  angular.json
  projects/knora/authentication/package.json
  projects/knora/authentication/src/lib/authentication.service.ts
  projects/knora/authentication/src/lib/interceptor/jwt.interceptor.ts
  projects/knora/authentication/src/lib/login-form/login-form.component.html
  projects/knora/authentication/src/lib/login-form/login-form.component.ts
  projects/knora/authentication/src/lib/session/session.service.ts
  projects/knora/core/src/lib/core.module.ts
  projects/knora/core/src/lib/services/admin/status-msg.service.ts
  projects/knora/core/src/lib/services/admin/users.service.spec.ts
  projects/knora/core/src/lib/services/admin/users.service.ts
  projects/knora/core/src/lib/services/api.service.ts
  projects/knora/core/src/lib/services/v2/resource.service.ts
  projects/knora/core/src/lib/services/v2/search-params.service.ts
  projects/knora/core/src/lib/services/v2/search.service.ts
  projects/knora/core/src/lib/services/v2/store.service.ts
  projects/knora/search/src/lib/extended-search/extended-search.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-ontology/select-ontology.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/boolean-value/boolean-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/date-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/header-calendar/header-calendar.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/decimal-value/decimal-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/integer-value/integer-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/text-value/text-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/uri-value/uri-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-resource-class/select-resource-class.component.spec.ts
  projects/knora/search/src/lib/search.component.spec.ts
  projects/knora/viewer/src/lib/property/link-value/link-value.component.spec.ts
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.spec.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.spec.ts
  src/app/app-init.service.ts
  src/app/app.module.ts
  src/app/knora-ui-examples/core-demo/users/users.component.ts
  src/config/config.dev.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/main.ts
Labels: breaking, enhancement

#186 Core: Fix issue in projects service
  projects/knora/core/src/lib/services/admin/projects.service.spec.ts
  projects/knora/core/src/lib/services/admin/projects.service.ts
  projects/knora/core/src/lib/services/admin/users.service.ts
Labels: bug

#187 feature (core): add additional user methods
  projects/knora/core/src/lib/services/admin/users.service.ts
Labels: feature

#163 @knora/viewer: grid & table views
  package.json
  projects/knora/viewer/README.md
  projects/knora/viewer/package.json
  projects/knora/viewer/src/lib/assets/style/viewer.scss
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.html
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.scss
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.spec.ts
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.ts
  projects/knora/viewer/src/lib/view/list-view/list-view.component.html
  projects/knora/viewer/src/lib/view/list-view/list-view.component.scss
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.spec.ts
  projects/knora/viewer/src/lib/view/table-view/table-view.component.ts
  projects/knora/viewer/src/lib/viewer.module.ts
  yarn.lock
Labels: enhancement
