Repository dasch-swiss/knora-ui, pull requests merged in 2019-06, with the labels that each got.

#239 fix(viewer-demo): Fix list
  .travis.yml
  src/app/knora-ui-examples/viewer-demo/properties/properties.component.ts
Labels: bug

#237 fix(core): Update system admin
  .travis.yml
  projects/knora/core/src/lib/services/admin/users.service.ts
Labels: enhancement

#234 Restrict fulltext search to a project
  projects/knora/core/src/lib/services/v2/search.service.spec.ts
  projects/knora/core/src/lib/services/v2/search.service.ts
  projects/knora/core/src/lib/test-data/resources/Testthing-expanded.json
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.ts
  projects/knora/viewer/src/lib/view/kui-view.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.spec.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
Labels: enhancement

#243 fix(yarn): fix vulnerability with handlebars and js-yaml
  yarn.lock
Labels: warning

#241 fix(viewer): Get list of results only once
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
Labels: bug

#221 style(search): Fix style issue in search-menu
  package.json
  projects/knora/action/ng-package.json
  projects/knora/authentication/ng-package.json
  projects/knora/authentication/ng-package.prod.json
  projects/knora/core/ng-package.json
  projects/knora/core/ng-package.prod.json
  projects/knora/search/ng-package.json
  projects/knora/search/ng-package.prod.json
  projects/knora/search/package.json
  projects/knora/search/src/lib/assets/style/_mixins.scss
  projects/knora/search/src/lib/assets/style/search.scss
  projects/knora/search/src/lib/expert-search/expert-search.component.html
  projects/knora/search/src/lib/extended-search/extended-search.component.html
  projects/knora/search/src/lib/extended-search/extended-search.component.scss
  projects/knora/search/src/lib/extended-search/extended-search.component.ts
  projects/knora/search/src/lib/extended-search/select-ontology/select-ontology.component.html
  projects/knora/search/src/lib/extended-search/select-ontology/select-ontology.component.ts
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.html
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/boolean-value/boolean-value.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/date-value.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/date-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/header-calendar/header-calendar.component.scss
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/header-calendar/header-calendar.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/decimal-value/decimal-value.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/decimal-value/decimal-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/integer-value/integer-value.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/integer-value/integer-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/text-value/text-value.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/text-value/text-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/uri-value/uri-value.component.html
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/uri-value/uri-value.component.ts
  projects/knora/search/src/lib/extended-search/select-resource-class/select-resource-class.component.html
  projects/knora/search/src/lib/extended-search/select-resource-class/select-resource-class.component.ts
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.html
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.scss
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.html
  projects/knora/search/src/lib/search-panel/search-panel.component.scss
  projects/knora/search/src/lib/search-panel/search-panel.component.ts
  projects/knora/search/src/lib/search.module.ts
  projects/knora/viewer/ng-package.json
  projects/knora/viewer/ng-package.prod.json
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
Labels: enhancement, refactor, styling

#228 docs: Update documentation
  .codacy.yml
  README.md
  docs/assets/scripts/prism.js
  docs/assets/style/_prism.scss
  docs/data/documentation/action/message.json
  docs/data/documentation/search/expert-search.json
  docs/data/documentation/viewer/search-results.json
  docs/main.js
  docs/main.js.map
  docs/polyfills.js
  docs/scripts.js
  docs/scripts.js.map
  docs/styles.js
  docs/styles.js.map
  projects/knora/action/src/lib/message/message.component.ts
  src/assets/scripts/prism.js
  src/assets/style/_prism.scss
  src/data/documentation/action/message.json
  src/data/documentation/search/expert-search.json
  src/data/documentation/viewer/search-results.json
Labels: documentation

#218 @knora/core: change to knora-admin
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
Labels: breaking

#248 fix(codacy): Fix codacy issues
  .codacy.yml
  .eslintignore
  .eslintrc.json
  .markdownlint.json
  .remarkrc.json
  README.md
  karma.conf.js
  package.json
  update_docs.sh
Labels: refactor, warning

#236 feat(core): Get version of Knora
  README.md
  package.json
  projects/knora/authentication/src/lib/authentication.service.ts
  projects/knora/core/README.md
  projects/knora/core/package.json
  projects/knora/core/src/lib/declarations/api-service-error.ts
  projects/knora/core/src/lib/declarations/api-service-result.ts
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/core/src/lib/services/admin/groups.service.spec.ts
  projects/knora/core/src/lib/services/admin/lists.service.spec.ts
  projects/knora/core/src/lib/services/admin/projects.service.spec.ts
  projects/knora/core/src/lib/services/admin/users.service.spec.ts
  projects/knora/core/src/lib/services/api.service.spec.ts
  projects/knora/core/src/lib/services/api.service.ts
  projects/knora/core/src/lib/services/v2/ontology-cache.service.spec.ts
  projects/knora/core/src/lib/services/v2/search.service.spec.ts
  src/app/knora-ui-examples/viewer-demo/properties/properties.component.ts
  yarn.lock
Labels: enhancement

#245 feat(search): Search panel
  .codacy.yml
  docs/app/knora-ui-examples/search-demo/search-panel/search-panel.component.ts
  docs/data/documentation/search/expert-search.json
  docs/data/documentation/search/fulltext-search.json
  docs/data/documentation/search/readme.md
  docs/data/documentation/search/search-panel-example.png
  docs/data/documentation/search/search-panel.json
  docs/data/documentation/search/search.json
  docs/main.js
  docs/main.js.map
  docs/polyfills.js
  docs/styles.js
  docs/styles.js.map
  package.json
  projects/knora/search/README.md
  projects/knora/search/src/lib/assets/images/filter.svg
  projects/knora/search/src/lib/expert-search/expert-search.component.html
  projects/knora/search/src/lib/expert-search/expert-search.component.scss
  projects/knora/search/src/lib/expert-search/expert-search.component.spec.ts
  projects/knora/search/src/lib/expert-search/expert-search.component.ts
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.html
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.html
  projects/knora/search/src/lib/search-panel/search-panel.component.spec.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.ts
  projects/knora/search/src/lib/search.component.ts
  projects/knora/search/src/lib/search.module.ts
  projects/knora/search/src/public_api.ts
  src/app/knora-ui-examples/search-demo/search-panel/search-panel.component.ts
  src/data/documentation/search/expert-search.json
  src/data/documentation/search/fulltext-search.json
  src/data/documentation/search/readme.md
  src/data/documentation/search/search-panel-example.png
  src/data/documentation/search/search-panel.json
  src/data/documentation/search/search.json
Labels: enhancement

#253 chore: Remove google api
  angular.json
  package.json
  projects/knora/action/src/lib/admin-image/admin-image.directive.ts
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  src/app/knora-ui-examples/action-demo/progress-indicator/progress-indicator.component.html
  src/assets/fonts/roboto-v19-latin-300.eot
  src/assets/fonts/roboto-v19-latin-300.svg
  src/assets/fonts/roboto-v19-latin-300.ttf
  src/assets/fonts/roboto-v19-latin-300.woff
  src/assets/fonts/roboto-v19-latin-300.woff2
  src/assets/fonts/roboto-v19-latin-500.eot
  src/assets/fonts/roboto-v19-latin-500.svg
  src/assets/fonts/roboto-v19-latin-500.ttf
  src/assets/fonts/roboto-v19-latin-500.woff
  src/assets/fonts/roboto-v19-latin-500.woff2
  src/assets/fonts/roboto-v19-latin-700.eot
  src/assets/fonts/roboto-v19-latin-700.svg
  src/assets/fonts/roboto-v19-latin-700.ttf
  src/assets/fonts/roboto-v19-latin-700.woff
  src/assets/fonts/roboto-v19-latin-700.woff2
  src/assets/fonts/roboto-v19-latin-italic.eot
  src/assets/fonts/roboto-v19-latin-italic.svg
  src/assets/fonts/roboto-v19-latin-italic.ttf
  src/assets/fonts/roboto-v19-latin-italic.woff
  src/assets/fonts/roboto-v19-latin-italic.woff2
  src/assets/fonts/roboto-v19-latin-regular.eot
  src/assets/fonts/roboto-v19-latin-regular.svg
  src/assets/fonts/roboto-v19-latin-regular.ttf
  src/assets/fonts/roboto-v19-latin-regular.woff
  src/assets/fonts/roboto-v19-latin-regular.woff2
  src/assets/style/_config.scss
  src/assets/style/_font.scss
  src/assets/style/main.scss
  src/index.html
  src/styles.scss
  yarn.lock
Labels: enhancement, styling

#252 fix(search): Edit position buttons of expert search form
  projects/knora/search/src/lib/assets/style/search.scss
  projects/knora/search/src/lib/expert-search/expert-search.component.scss
  projects/knora/search/src/lib/expert-search/expert-search.component.ts
  projects/knora/search/src/lib/extended-search/extended-search.component.scss
  projects/knora/search/src/lib/extended-search/extended-search.component.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.html
Labels: bug, styling

#255 fix(viewer): Reload search results
  .circleci/config.yml
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.spec.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
Labels: bug

#256 style(viewer): Add style to the connection links
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.html
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.scss
Labels: styling

#258 style(search): Fix size issue in search log list
  projects/knora/search/README.md
  projects/knora/search/package.json
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.html
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.scss
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.spec.ts
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.spec.ts
  projects/knora/search/tsconfig.lib.json
  tsconfig.json
Labels: styling

#259 chore: Update to es2018
  projects/knora/action/ng-package.json
  projects/knora/action/ng-package.prod.json
  projects/knora/action/src/lib/action.module.ts
  projects/knora/action/src/lib/admin-image/admin-image.directive.ts
  projects/knora/action/tsconfig.lib.json
  projects/knora/authentication/tsconfig.lib.json
  projects/knora/core/tsconfig.lib.json
  projects/knora/search/tsconfig.lib.json
  projects/knora/viewer/tsconfig.lib.json
Labels: enhancement
