Repository dasch-swiss/knora-ui, pull requests merged in 2019-12, with the labels that each got.

#374 Simple resource viewer with knora-api-js-lib
  projects/knora/action/src/lib/pipes/truncate.pipe.ts
  projects/knora/viewer/src/lib/assets/style/viewer.scss
  projects/knora/viewer/src/lib/property/boolean-value/boolean-value.component.html
  projects/knora/viewer/src/lib/property/boolean-value/boolean-value.component.ts
  projects/knora/viewer/src/lib/property/color-value/color-value.component.html
  projects/knora/viewer/src/lib/property/color-value/color-value.component.ts
  projects/knora/viewer/src/lib/property/date-value/date-value.component.ts
  projects/knora/viewer/src/lib/property/decimal-value/decimal-value.component.ts
  projects/knora/viewer/src/lib/property/geometry-value/geometry-value.component.html
  projects/knora/viewer/src/lib/property/geometry-value/geometry-value.component.ts
  projects/knora/viewer/src/lib/property/integer-value/integer-value.component.html
  projects/knora/viewer/src/lib/property/integer-value/integer-value.component.ts
  projects/knora/viewer/src/lib/property/interval-value/interval-value.component.html
  projects/knora/viewer/src/lib/property/interval-value/interval-value.component.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-html/text-value-as-html.component.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-string/text-value-as-string.component.html
  projects/knora/viewer/src/lib/property/text-value/text-value-as-string/text-value-as-string.component.ts
  projects/knora/viewer/src/lib/property/textfile-value/textfile-value.component.html
  projects/knora/viewer/src/lib/property/textfile-value/textfile-value.component.ts
  projects/knora/viewer/src/lib/property/uri-value/uri-value.component.ts
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.scss
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.ts
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.html
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.scss
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.ts
  projects/knora/viewer/src/lib/view/list-view/list-view.component.html
  projects/knora/viewer/src/lib/view/list-view/list-view.component.ts
  projects/knora/viewer/src/lib/view/properties-view/properties-toolbar/properties-toolbar.component.html
  projects/knora/viewer/src/lib/view/properties-view/properties-toolbar/properties-toolbar.component.scss
  projects/knora/viewer/src/lib/view/properties-view/properties-toolbar/properties-toolbar.component.spec.ts
  projects/knora/viewer/src/lib/view/properties-view/properties-toolbar/properties-toolbar.component.ts
  projects/knora/viewer/src/lib/view/properties-view/properties-view.component.html
  projects/knora/viewer/src/lib/view/properties-view/properties-view.component.scss
  projects/knora/viewer/src/lib/view/properties-view/properties-view.component.ts
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.html
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.scss
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
  projects/knora/viewer/src/lib/viewer.module.ts
Labels: enhancement

#371 Fix tests in search module
  .circleci/config.yml
  .gitignore
  .travis.yml
  projects/knora/action/src/lib/login-form/login-form.component.spec.ts
  projects/knora/search/src/lib/expert-search/expert-search.component.spec.ts
  projects/knora/search/src/lib/extended-search/extended-search.component.spec.ts
  projects/knora/search/src/lib/extended-search/extended-search.component.ts
  projects/knora/search/src/lib/extended-search/select-ontology/select-ontology.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/select-property.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/boolean-value/boolean-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/date-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/date-value/header-calendar/header-calendar.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/decimal-value/decimal-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/integer-value/integer-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/link-value/link-value.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-display/list-display.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/specify-property-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/text-value/text-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/uri-value/uri-value.component.spec.ts
  projects/knora/search/src/lib/extended-search/select-resource-class/select-resource-class.component.spec.ts
  projects/knora/search/src/lib/fulltext-search/fulltext-search.component.spec.ts
  projects/knora/search/src/lib/search-panel/search-panel.component.spec.ts
  yalc.lock
Labels: stage/in-progress, testing

#381 Viewer: Search results improvements
  README.md
  projects/knora/action/src/lib/login-form/login-form.component.spec.ts
  projects/knora/action/src/lib/progress-indicator/progress-indicator.component.spec.ts
  projects/knora/search/src/lib/expert-search/expert-search.component.scss
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.html
  projects/knora/viewer/src/lib/view/search-results/search-results.component.scss
  projects/knora/viewer/src/lib/view/search-results/search-results.component.ts
  projects/knora/viewer/src/lib/viewer.module.ts
Labels: bug, enhancement, refactor

#387 Update properties depending on knora-api-js-lib
  .circleci/config.yml
  .travis.yml
  projects/knora/viewer/src/lib/property/date-value/date-value.component.ts
  projects/knora/viewer/src/lib/property/external-res-value/external-res-value.component.html
  projects/knora/viewer/src/lib/property/external-res-value/external-res-value.component.scss
  projects/knora/viewer/src/lib/property/external-res-value/external-res-value.component.spec.ts
  projects/knora/viewer/src/lib/property/external-res-value/external-res-value.component.ts
  projects/knora/viewer/src/lib/property/index.ts
  projects/knora/viewer/src/lib/property/link-value/link-value.component.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-html/text-value-as-html.component.ts
  projects/knora/viewer/src/lib/viewer.module.ts
  yalc.lock
Labels: enhancement

#385 Fix tests in the viewer module
  .circleci/config.yml
  .travis.yml
  projects/knora/viewer/src/lib/property/boolean-value/boolean-value.component.spec.ts
  projects/knora/viewer/src/lib/property/color-value/color-value.component.spec.ts
  projects/knora/viewer/src/lib/property/date-value/date-value.component.spec.ts
  projects/knora/viewer/src/lib/property/decimal-value/decimal-value.component.spec.ts
  projects/knora/viewer/src/lib/property/geometry-value/geometry-value.component.spec.ts
  projects/knora/viewer/src/lib/property/geoname-value/geoname-value.component.spec.ts
  projects/knora/viewer/src/lib/property/integer-value/integer-value.component.spec.ts
  projects/knora/viewer/src/lib/property/interval-value/interval-value.component.spec.ts
  projects/knora/viewer/src/lib/property/link-value/link-value.component.spec.ts
  projects/knora/viewer/src/lib/property/list-value/list-value.component.html
  projects/knora/viewer/src/lib/property/list-value/list-value.component.spec.ts
  projects/knora/viewer/src/lib/property/list-value/list-value.component.ts
  projects/knora/viewer/src/lib/property/text-value/text-value-as-string/text-value-as-string.component.spec.ts
  projects/knora/viewer/src/lib/property/textfile-value/textfile-value.component.spec.ts
  projects/knora/viewer/src/lib/property/textfile-value/textfile-value.component.ts
  projects/knora/viewer/src/lib/property/uri-value/uri-value.component.spec.ts
  projects/knora/viewer/src/lib/resource/still-image/still-image.component.spec.ts
  projects/knora/viewer/src/lib/view/grid-view/grid-view.component.spec.ts
  projects/knora/viewer/src/lib/view/list-view/list-view.component.spec.ts
  projects/knora/viewer/src/lib/view/properties-view/properties-toolbar/properties-toolbar.component.spec.ts
  projects/knora/viewer/src/lib/view/resource-view/resource-view.component.spec.ts
  projects/knora/viewer/src/lib/view/search-results/search-results.component.spec.ts
Labels: testing

#393 Rename ListNode to ListNodeV2
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-display/list-display.component.ts
  projects/knora/search/src/lib/extended-search/select-property/specify-property-value/list-value/list-value.component.ts
Labels: breaking, bug

#394 Clean core module from admin list service + declarations
  projects/knora/action/src/lib/login-form/login-form.component.spec.ts
  projects/knora/action/src/lib/string-literal-input/string-literal-input.component.spec.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list-create-payload.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list-info-response.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list-info-update-payload.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list-info.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list-node-info-response.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list-node-info.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list-node-response.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list-node-update-payload.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list-node.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list-response.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/list.ts
  projects/knora/core/src/lib/declarations/api/admin/lists/lists-response.ts
  projects/knora/core/src/lib/declarations/index.ts
  projects/knora/core/src/lib/services/admin/lists.service.spec.ts
  projects/knora/core/src/lib/services/admin/lists.service.ts
  projects/knora/core/src/lib/services/index.ts
  projects/knora/core/src/lib/test-data/admin/shared-test-data.ts
Labels: chore

#396 Pre release: version 10.0.0
  .circleci/config.yml
  .travis.yml
  README.md
  package.json
  projects/knora/action/README.md
  projects/knora/action/package.json
  projects/knora/core/README.md
  projects/knora/core/package.json
  projects/knora/core/src/lib/core.module.ts
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/search/README.md
  projects/knora/search/package.json
  projects/knora/viewer/README.md
  projects/knora/viewer/package.json
  yarn.lock
Labels: chore, enhancement

#398 Update prod config
  docs/404.html
  docs/config/config.prod.json
  docs/index.html
  docs/main.8d9d7a8c35437c539036.js
  src/config/config.prod.json
Labels: bug
