Repository dasch-swiss/knora-ui, pull requests merged in 2020-01, with the labels that each got.

#399 Fix missing delimiter in createOntology
  projects/knora/core/src/lib/services/v2/ontology.service.ts
Labels: bug

#401 Update prefix base url of the gravquery in expert search
  projects/knora/search/src/lib/expert-search/expert-search.component.spec.ts
  projects/knora/search/src/lib/expert-search/expert-search.component.ts
Labels: bug

#402 Resolve security alert about serialize-javascript
  yarn.lock
Labels: warning

#404 Upgrade knora-api-js-lib to v0.2.0
  package.json
  projects/knora/action/README.md
  projects/knora/action/package.json
  projects/knora/core/README.md
  projects/knora/core/package.json
  projects/knora/search/README.md
  projects/knora/search/package.json
  projects/knora/viewer/README.md
  projects/knora/viewer/package.json
  yarn.lock
Labels: chore, enhancement

#405 Pre release: version 10.0.1
  README.md
  package.json
  projects/knora/action/README.md
  projects/knora/action/package.json
  projects/knora/core/README.md
  projects/knora/core/package.json
  projects/knora/core/src/lib/declarations/api/knora-constants.ts
  projects/knora/search/README.md
  projects/knora/search/package.json
  projects/knora/viewer/README.md
  projects/knora/viewer/package.json
Labels: chore, documentation, enhancement

#406 Update documentation for v10.0.1
  docs/404.html
  docs/data/documentation/action/readme.md
  docs/data/documentation/core/ontology.json
  docs/data/documentation/core/readme.md
  docs/data/documentation/demo/readme.md
  docs/data/documentation/search/expert-search.json
  docs/data/documentation/search/readme.md
  docs/data/documentation/viewer/readme.md
  docs/index.html
  docs/main.8d9d7a8c35437c539036.js
  docs/main.a60eeacaab7a2bbed1ee.js
  docs/polyfills-es5.926624883e7bb97fd4f4.js
  docs/polyfills-es5.e6d296dd0d03fc7a3c60.js
  docs/polyfills.4a94f528d3e9fc927589.js
  docs/polyfills.bfe640ea27a2d460b91d.js
  docs/runtime.458556a34b891ea32398.js
  docs/scripts.9f6114cbbdf01b47646d.js
  docs/scripts.f59ed06881bc4dcf7bef.js
  docs/styles.4f97cd4d2f4d62d0f7be.css
  docs/styles.fa6aa457dd9027c6ccce.css
  src/data/documentation/action/readme.md
  src/data/documentation/core/ontology.json
  src/data/documentation/core/readme.md
  src/data/documentation/demo/readme.md
  src/data/documentation/search/expert-search.json
  src/data/documentation/search/readme.md
  src/data/documentation/viewer/readme.md
Labels: documentation
